[package]
name = "yhlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
]

[dependencies]
log = "0.4.20"
num-bigint = "0.4.4"
num-traits = "0.2.17"
rstest = "0.18.2"


